baseURL = 'https://uberate.github.io/learn'

title="Learn / Ub(s)erate"

theme = "blowfish"

# 主题系列：Blowfish, Avocado, Fire, Ocean, Forest
colorScheme="Ocean"

languageCode = "zh-cn"
languageName = "简体中文"

enableGitInfo = true
enableRobotsTXT = true
enableCodeCopy = true

hasCJKLanguage=true

[params]
colorScheme="Ocean"
dateFormat="2006-01-02 15:04:05"
timeZone = "Asia/Shanghai"

[params.article]
heroStyle = "background"
showHero = true
showBreadcrumbs = true
showTaxonomies = true
showTableOfContents = true
showPagination = false
showDateUpdated = true

[params.homepage]
layout = "card"
homepageImage = "img/homepage_img.jpeg"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"